// Every route in the product. ARCHITECH has one entry point (the dashboard) and one place
// to work (a project), so there is no standalone workspace, Learn or Challenge page.
//
//   /                       redirects to /dashboard
//   /dashboard              project dashboard
//   /workspace/[projectId]  a project, in Learn or Challenge mode

export const HOME_ROUTE = "/dashboard";

// Routes that used to be standalone pages. They no longer exist; they only redirect home.
export const RETIRED_ROUTES = ["/workspace", "/learn", "/challenge"] as const;

// Ids are generated by the store, but they come back from storage and the URL, so they are
// encoded before they are put into a path.
export const projectRoute = (projectId: string) => `/workspace/${encodeURIComponent(projectId)}`;
